//Include any postdeployment steps here, such as steps necessary to test that the deployment was successful. If there are no postdeployment steps leave this file empty.

== Postdeployment steps

=== (Optional) Add your SSL certificate to the Application Load Balancer

If you did not provide an SSL certificate during the Partner Solution deployment, edit the listener to configure an SSL certificate.

. Open the https://console.aws.amazon.com/ec2/[Amazon EC2^] console.

. In the navigation pane, under *Load Balancing*, choose *Load Balancers*.

. Select the load balancer and choose *Listeners*.

. Select the check box for the listener and then choose *Edit*.

. For *Protocol*, choose *HTTPS*.

. Choose *Update*.

. Change the default Secure Socket Layer (SSL) certificate. For *Default SSL certificate*, do one of the following:

** If you created or https://docs.aws.amazon.com/acm/latest/userguide/import-certificate.html[imported^] a certificate using AWS Certificate Manager, choose *From ACM* and choose the certificate.

** If you uploaded a certificate using IAM, choose *From IAM* and choose the certificate.

** If you have a certificate that isn't managed by ACM or IAM, https://docs.aws.amazon.com/acm/latest/userguide/import-certificate.html[import^] it to ACM and add it to your listener. For more information, refer to https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-listeners.html[Listeners for your Network Load Balancer^].

=== (Optional) Create a CNAME record in your DNS provider

If you did not provide a Route 53 hosted zone ID during the Partner Solution installation, you must create the following three DNS records.

. 3decision user URI: `3decision.<your domain>`.

. 3decision API URI: `3decision-api.<your domain>`.

. 3decision help URI: `3decision-help.<your domain>`.

Both records must target the 3decision Application Load Balancer. To obtain the address of the Application Load Balancer, open the https://console.aws.amazon.com/ec2/[Amazon EC2^] console. In the navigation pane, under *Load Balancing*, choose *Load Balancers*. The address of the Application Load Balancer is in the *DNS Name* column. For more information, refer to https://docs.aws.amazon.com/elasticloadbalancing/latest/network/network-load-balancers.html[Network Load Balancers^].

=== Additional information

==== Infrastructure monitoring and log collection

This Partner Solution does not include infrastructure monitoring or log collection. 3decision updates are provided as Helm charts updates. Although these updates are free, you must apply Helm upgrades manually to the deployed EKS cluster.

==== Data administration

In 3decision, the data owner (the users that uploads the structure to 3decision or is granted ownership by another user) manages data administration.

==== User access management

Configure user access management in the authentication provider (Okta or Azure) by granting access to the OpenID Connect application. For more information, refer to link:#_authentication_provider[Authentication provider], earlier in this guide. By default, the data access policy in 3decision denies access to private data. Users can only access public data by default.

==== Operations and security

By default, Amazon RDS and Amazon EBS backup databases and volumes, respectively. You can create a new 3decision environment from backups using the solution's CloudFormation template.

You do not need to manage patching of AWS managed services. You must maintain security patching of the optional bastion host if you choose to deploy it.

Consult your Discngine representative for information about available deployment and maintenance services and upload requirements.

3decision synchronizes with public structures made available by the Research Collaboratory for Structural Bioinformatics Protein Data Bank (RCSB PDB). Data synchronization uses the rsync protocol. 3decision calls the following domains:

* `rsync.ebi.ac.uk` on port 873.

* `rsync.wwpdb.org` on ports 873 and 33444.

3decision in this Partner Solution supports updating 3decision from the command line. Contact Discngine for 3decision update commands and instructions. For more information about 3decision SaaS with continuous deployment, contact your Discngine representative.

==== Testing and verification

This Partner Solution does not currently support automated testing. Although each 3decision microservice provides a liveness and readiness endpoint, you must configure monitoring probes.

==== Database size and instance type

The recommended database instance type for up to 20 concurrent users is `t3.xlarge`. You can choose the database instance type during deployment. The deployed Amazon RDS for Oracle database storage is 1TB (extensible to 3TB). Amazon EBS overall storage is ~1.2TB.

For costs and licenses information, refer to the https://fwd.aws/tA69w?[AWS Partner Solution General Information Guide^] or contact your Discngine sales representative.



*Q*: what is the minimal kubernetes nodes specs ?

*A*: Customers are using application in different ways, and config may differ.

The minimal configuration is 3 nodes. Shape size should be kept as 3 * t3.xlarge.


*Q*: Sizing for cost estimates approach?

*A*:


