//Include any postdeployment steps here, such as steps necessary to test that the deployment was successful. If there are no postdeployment steps leave this file empty.

== Postdeployment steps

=== (Optional) Add your SSL certificate to the Application Load Balancer

If you did not provide an SSL certificate during the Quick Start deployment, edit the listener to configure an SSL certificate.

. Open the https://console.aws.amazon.com/ec2/[Amazon EC2] console.

. In the navigation pane, under *Load Balancing*, choose *Load Balancers*.

. Select the load balancer and choose *Listeners*.

. Select the check box for the listener and then choose *Edit*.

. For *Protocol*, choose *HTTPS*.

. Choose *Update*.

. Change the default Secure Socket Layer (SSL) certificate. For *Default SSL certificate*, do one of the following:

** If you created or https://docs.aws.amazon.com/acm/latest/userguide/import-certificate.html[imported] a certificate using AWS Certificate Manager, choose *From ACM* and choose the certificate.

** If you uploaded a certificate using IAM, choose *From IAM* and choose the certificate.

** If you have a certificate that isn't managed by ACM or IAM, https://docs.aws.amazon.com/acm/latest/userguide/import-certificate.html[import] it to ACM and add it to your listener. For more information, refer to https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-listeners.html[Listeners for your Network Load Balancer].


=== (Optional) Create a CNAME record in your DNS provider

If you did not provide a Route 53 hosted zone ID during the Quick Start installation, you must create the following two DNS records.

. 3decision user UI: `3decision.<your domain>`.

. 3decision administrator UI: `3decision-etl.<your domain>`.

Both records must target the 3decision Application Load Balancer. To obtain the address of the Application Load Balancer, open the https://console.aws.amazon.com/ec2/[Amazon EC2] console. In the navigation pane, under *Load Balancing*, choose *Load Balancers*. The address of the Application Load Balancer is in the *DNS Name* column. For more information, refer to https://docs.aws.amazon.com/elasticloadbalancing/latest/network/network-load-balancers.html[Network Load Balancers].

=== (Optional) Create additional accounts

The Quick Start creates a 3decision user named `3decision`. (You can change the default name during deployment.) Additional user accounts can be created in the 3decision administrator UI. 

. Navigate to `\https://3decision-etl.<your domain>`.

. Log in with the account `3decision` and the password you provided during deployment.

. Under *Admin Pages*, *Security*, choose *Users*.

. Enter *User Name*, *Password*, and *Confirm Password*.

. Choose *Add*.

=== Additional information

This Quick Start does not include the following:

* Azure and Okta OpenID Connect authentication. Only local accounts are supported.

* Infrastructure monitoring.

* Log collection.

3decision updates are provided as Helm charts updates. Although these updates are free, you must manually apply Helm upgrades to the deployed EKS cluster.