//Include any postdeployment steps here, such as steps necessary to test that the deployment was successful. If there are no postdeployment steps leave this file empty.

== Postdeployment steps

=== (Optional) Add your SSL certificate to the Application Load Balancer

If you did not provide an SSL certificate during the Partner Solution deployment, edit the listener to configure an SSL certificate.

. Open the https://console.aws.amazon.com/ec2/[Amazon EC2] console.

. In the navigation pane, under *Load Balancing*, choose *Load Balancers*.

. Select the load balancer and choose *Listeners*.

. Select the check box for the listener and then choose *Edit*.

. For *Protocol*, choose *HTTPS*.

. Choose *Update*.

. Change the default Secure Socket Layer (SSL) certificate. For *Default SSL certificate*, do one of the following:

** If you created or https://docs.aws.amazon.com/acm/latest/userguide/import-certificate.html[imported] a certificate using AWS Certificate Manager, choose *From ACM* and choose the certificate.

** If you uploaded a certificate using IAM, choose *From IAM* and choose the certificate.

** If you have a certificate that isn't managed by ACM or IAM, https://docs.aws.amazon.com/acm/latest/userguide/import-certificate.html[import] it to ACM and add it to your listener. For more information, refer to https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-listeners.html[Listeners for your Network Load Balancer].

=== (Optional) Create a CNAME record in your DNS provider

If you did not provide a Route 53 hosted zone ID during the Partner Solution installation, you must create the following three DNS records.

. 3decision user URI: `3decision.<your domain>`.

. 3decision API URI: `3decision-api.<your domain>`.

. 3decision help URI: `3decision-help.<your domain>`.

Both records must target the 3decision Application Load Balancer. To obtain the address of the Application Load Balancer, open the https://console.aws.amazon.com/ec2/[Amazon EC2] console. In the navigation pane, under *Load Balancing*, choose *Load Balancers*. The address of the Application Load Balancer is in the *DNS Name* column. For more information, refer to https://docs.aws.amazon.com/elasticloadbalancing/latest/network/network-load-balancers.html[Network Load Balancers].

=== Additional information

This Partner Solution does not include the following:

* Infrastructure monitoring.

* Log collection.

3decision updates are provided as Helm charts updates. Although these updates are free, you must manually apply Helm upgrades to the deployed EKS cluster.