//Include any predeployment steps here, such as signing up for a Marketplace AMI or making any changes to a Partner account. If there are none leave this file empty.

== Predeployment steps

=== Administrator privileges

To deploy the Partner Solution, you must have an administrator account with permissions to deploy the resources the Partner Solution contains, which include IAM roles. IAM roles deployed by this Partner Solution follow the principle of least privilege.

=== Authentication

During deployment, you are prompted to provide information about your authentication provider. 3decision supports OpenID Connect for both Azure and Okta. Refer to the following instructions to create Azure and Okta OpenID Connect applications.

==== Creating an Azure OpenID Connect application

. Sign in to the Azure portal using an account with administrator permissions.
. Choose *Azure Active Directory*.
. Under *App registrations*, choose *New registration*.
. Enter a name for your application (for example, `Discngine 3decision prod`).
. For *Redirect URI*, enter the following. Replace `<your domain>` and `<your_top_level_domain>` in the URI shown with your information (for example, `discngine.com`).

+
`\https://3decision-api.<your_domain>.<your_top_level_domain>/auth/azure/callback`

[start=5]
. Choose *Register*.
. In the *Authentication* section of your application, under *Implicit grant and hybrid flows*, select *ID Token* to enable ID tokens.
. In the *Token configuration* section, add the following optional claims to the ID token:
- `email`
- `prefered_username`
- `family_name`
- `given_name`

. On the *Certificates & secrets* page, generate a new secret and copy it. You'll use it during the Partner Solution deployment.
. On the *Overview* page, choose the *Endpoints* tab.
. Copy the URL in *OpenID Connect metadata document*. You'll use it during the Partner Solution deployment.

. In the Azure portal, navigate to *Enterprise Applications*
. Choose your 3decision application and open it
. Navigate to *Properties*
. Set * Assignment required?* to Yes if you want to filter out users that are not a member of this application.

==== Creating an Okta OpenID Connect application

. In the Okta Admin Console, under *Applications*, choose *Applications*.
. Choose *Create app integration*.
. For *Sign In* method, choose *OIDC - OpenID Connect*.
. For the application type, choose *Web Application*.
. Choose *Next*.
. Name the application `3decision prod`.
. For *Grant type*, choose *Client Credentials*.
. Select *Refresh Token*.
. For *Sign-in redirect URI*, enter the following. Replace `<your domain>` and `<your_top_level_domain>` in the URI shown with your information (for example, `discngine.com`).

+
`\https://3decision-api.<you_domain>.<your_top_level_domain>/auth/okta/callback`

[start=8]
. On the *Assignments* tab, under *Assign*, choose *Assign to Groups*. Choose group assignments to manage who will be able to access the application.
. Choose *Save*.
. Copy the secret, as you'll use it during the Partner Solution deployment.
. In the upper-right corner of the Okta dashboard, copy the Okta domain in the global header (for example, `example.okta-emea.com`). You'll use it during the Partner Solution deployment.

During Partner Solution deployment, you can choose `default` as your Okta server ID. 3decision will use the scopes `email`, `profile`, `openid`, and `offline_access` and the claims `email` and `name` from the ID token. For more information, refer to https://help.okta.com/en/prod/Content/Topics/Apps/Apps_App_Integration_Wizard_OIDC.htm[Create OIDC app integrations using AIW].

=== VPC Tagging

If you are deploying 3decision in an existing VPC, ensure that the private subnets have the correct tags. The tag *kubernetes.io/role/elb* needs to be added on each public subnet and the tag *kubernetes.io/role/internal-elb* on each private subnet. The value of the tags should remain empty.

=== Encrypting the Database

The RDS database created during the deployment is based on a public unencrypted snapshot. To use an encrypted database snapshot, create and encrypt a copy of the default snapshot.

To find the default snapshot:

. Navigate to the https://console.aws.amazon.com/rds/[Amazon RDS console^].
. In the navigation pane, choose *Snapshots*.
. Choose the *Public* tab to find the latest version of the `db3dec` snapshot.

Enter the ARN of the snapshot copy in the *Database snapshot identifier* (`DBSnapShotIdentifier`) parameter during deployment.