//Include any predeployment steps here, such as signing up for a Marketplace AMI or making any changes to a Partner account. If there are none leave this file empty.

== Predeployment steps

=== Authentication

During deployment, you are prompted to provide information about your authentication provider. 3decision supports OpenID Connect for both Azure and Okta.

==== Creating an Azure OpenID Connect application

. Use Open Connect to connect to your Azure portal (you need permissions to create an App)
. Under *App registrations*, choose *New registration*.
. Enter a name for your application (for example, `Discngine 3decision prod`).
. For *Redirect URL*, enter the following URL. Replace <your domain> and <your_top_level_domain> with your information (for example, `discngine.com`).

+
`\https://api.3decision.<you_domain>.<your_top_level_domain>/auth/azure/callback`

[start=5]
. Choose *Register*.
. In the *Authentication* section of your application, under *Implicit grant and hybrid flows*, select *ID Token* to enable ID tokens.
. In the *Token configuration* section, add the following optional claims to the ID token:
- `email`
- `prefered_username`
- `family_name`
- `given_name`

. On the *Certificates & secrets* page, generate a new secret and copy it. You'll use it during the Quick Start deployment.
. On the *Overview* page, choose the *Endpoints* tab.
. Copy the URL in *OpenID Connect metadata document*. You'll use it during the Quick Start deployment.

==== Creating an Okta OpenID Connect application

. In the *Applications/Applications* section, create a new application.
. For *Sign In* method, choose *OIDC*.
. For *Application type*, choose *Web Application*.
. Name the application `3decision prod`.
. For grant type, select *Client Credentials*.
. Select *Refresh Token*.
. For *Sign-in redirect URI*, enter the following. Replace <your domain> and <your_top_level_domain> with your information (for example, `discngine.com`).

+
`\https://api.3decision.<you_domain>.<your_top_level_domain>/auth/azure/callback`

[start=8]
. Choose group assignements to manage who will be able to access the app.
. Choose *Save*.
. Copy the secret, as you'll use it during the Quick Start deployment.
. In the upper-right corner of the Okta dashboard, copy the Okta domain in the global header (for example, `example.okta-emea.com`).

During Quick Start deployment, you can choose `default` as your Okta server ID. 3decision will use the scopes `email`, `profile`, `openid`, and `offline_access` and the claims `email` and `name` from the ID token.

=== VPC Tagging

If you are deploying 3decision in an existing VPC, ensure that the private subnets have the correct tags. For more information, refer to https://aws-quickstart.github.io/quickstart-amazon-eks/#_launch_the_quick_start[Amazon EKS on the AWS Cloud].

=== FAQ before deployment

*Q*: Will 3decision make HTTP calls to internet websites?

*A*: Yes, 3decision synchronizes with public structures made available by the RCSB. The data synchronization uses the Rsync protocol. 
Domains that are called are:

  * rsync.ebi.ac.uk on port 873
  * rsync.wwpdb.org on port 873 and 33444




*Q*: Why does Azure require additional claims and not Okta ?

*A*: Default Okta ID Token claims are enough. Azure require extra claims for 3decision to work.
