//Include any predeployment steps here, such as signing up for a Marketplace AMI or making any changes to a Partner account. If there are none leave this file empty.

== Predeployment steps

=== Administrator privileges

To deploy the Partner Solution, you must have an AWS administrator account with permissions to deploy the resources the Partner Solution contains, which include IAM roles. IAM roles deployed by this Partner Solution follow the principle of least privilege. For more information about the Partner Solution architecture, refer to link:#_architecture[Architecture], earlier in this guide.

=== Authentication provider

During deployment, you provide information about your authentication provider. 3decision supports LDAP and OpenID Connect authentication for Azure and Okta. Azure requires additional claims for 3decision to work with Azure. Refer to the following instructions to create Azure and Okta OpenID Connect applications.

==== Creating an Azure OpenID Connect application

. Sign in to the Azure portal using an account with administrator permissions.
. Choose *Azure Active Directory*.
. Under *App registrations*, choose *New registration*.
. Enter a name for your application (for example, `Discngine 3decision prod`).
. For *Redirect URI*, use URI format 1 to configure 3decision SaaS. Use URI format 2 for self-hosted.

.. URI format 1: SaaS.
+
Replace `<company>` with the name provided by your Discngine sales representative.
+
`\https://3decision-<company>-api.discngine.cloud/auth/azure/callback`

.. URI format 2: Self-hosted.
+
Replace `<your domain>` and `<your_top_level_domain>` in the URI shown with your information (for example, `discngine.com`).
+
`\https://3decision-api.<your_domain>.<your_top_level_domain>/auth/azure/callback`

[start=5]
. Choose *Register*.
. In the *Authentication* section of your application, under *Implicit grant and hybrid flows*, select *ID Token* to enable ID tokens.
. In the *Token configuration* section, add the following optional claims to the ID token:
- `email`
- `prefered_username`
- `family_name`
- `given_name`

. On the *Certificates & secrets* page, generate a new secret and copy it. You'll use it during the Partner Solution deployment.
. On the *Overview* page, choose the *Endpoints* tab.
. Copy the URL in *OpenID Connect metadata document*. You'll use it during the Partner Solution deployment.

. In the Azure portal, navigate to *Enterprise Applications*
. Choose your 3decision application and open it
. Navigate to *Properties*
. Set * Assignment required?* to Yes if you want to filter out users that are not a member of this application.

==== Creating an Okta OpenID Connect application

. In the Okta Admin Console, under *Applications*, choose *Applications*.
. Choose *Create app integration*.
. For *Sign In* method, choose *OIDC - OpenID Connect*.
. For the application type, choose *Web Application*.
. Choose *Next*.
. Name the application `3decision prod`.
. For *Grant type*, choose *Client Credentials*.
. Select *Refresh Token*.
. For *Sign-in redirect URI*, enter the following. Replace `<your domain>` and `<your_top_level_domain>` in the URI shown with your information (for example, `discngine.com`).

+
`\https://3decision-api.<you_domain>.<your_top_level_domain>/auth/okta/callback`

[start=8]
. On the *Assignments* tab, under *Assign*, choose *Assign to Groups*. Choose group assignments to manage who will be able to access the application.
. Choose *Save*.
. Copy the secret, as you'll use it during the Partner Solution deployment.
. In the upper-right corner of the Okta dashboard, copy the Okta domain in the global header (for example, `example.okta-emea.com`). You'll use it during the Partner Solution deployment.

During Partner Solution deployment, you can choose `default` as your Okta server ID. 3decision will use the scopes `email`, `profile`, `openid`, and `offline_access` and the claims `email` and `name` from the ID token. For more information, refer to https://help.okta.com/en/prod/Content/Topics/Apps/Apps_App_Integration_Wizard_OIDC.htm[Create OIDC app integrations using AIW].

In Only 1 ("user" type). The notion of user role in 3decision (3 roles exists) is business oriented and only affect the layout of the application.

The notion of "administrator" does not exist.

Administration of the data is managed by a very granular grant management of projects and structure access within the app by the owner of the data.
The owner of the data is the user that uploaded the structures in 3decision or a user that was granted the ownership.

=== VPC Tagging

Before deploying 3decision to an existing VPC, ensure that the public subnets have the *kubernetes.io/role/elb* tag and the private subnets have the *kubernetes.io/role/internal-elb* tag. The value of the tags should remain empty.

=== Encrypting the Database

The deployment creates an RDS database based on a public unencrypted snapshot. To encrypt the snapshot, first copy the latest version of the **db3dec<version>** snapshot and add encryption to the copy. For more information, refer to https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_CopySnapshot.html#copying_a_DB_snapshot[Copying a DB snapshot].

=== FAQ before deployment

==== Automation

*Q*: Concerning EC2 management, will there be any residual work needed for preparing the environment after the quickstart templates has been executed during deployment?

*A*: Only EKS managed nodes are deployed, and as such no further work is needed.

==== Authentication & Authorization:

*Q*: How many types of users/roles do we have?  (i.e. User vs. priviliged admin users)?

*A*: Only 1 ("user" type). The notion of user role in 3decision (3 roles exists) is business oriented and only affect the layout of the application.

The notion of "administrator" does not exist.

Administration of the data is managed by a very granular grant management of projects and structure access within the app by the owner of the data.
The owner of the data is the user that uploaded the structures in 3decision or a user that was granted the ownership.

This aspect is part of the training/onboarding.

*Q*: How do we manage access control and User Management within application!

*A*: User access management is performed at the level of the identity provicer (Azure, Okta) by granting/revoking acces to the Open ID connect application.

Access to the data to users is managed in the application by a data owners (people that uploaded the data or that are made owners).

Data access policy within the app is deny-by-default for private data.

Users can only public data by default.

==== AWS platform overview

*Q*: Any persistent nodes?

*A*: Yes the minimal shape of the kubernetes cluster is 3 nodes.

*Q*: Is all critical data located in the RDS ?

*A*: No, analysed data and metadata is stored in an Oracle RDS database. Your RAW data (uploaded structures and files) is also persisted on encrypted EBS volumes as a "datasafe".

*Q*: Loadbalancing / failover ?

*A*: The quickstart deploys an application load balancer (flexibility over network configuration is included in the cloudformation options, especially for Route53).


==== Operations & security:

*Q*: Backup options?

*A*: We highly recommend enabling RDS backups (done by default) and EBS volumes backups for failover/BCP: creating a new 3decision environement from backups using the cloudformation template is easy.

*Q*: Patch management (who and how is this handled?)

*A*: 3decision quickstart only use AWS managed services: EC2 nodes are managed by AWS. RDS database is AWS managed. No patching management is required.

*Q*: Security patching of Bastion host ?
*A*: By default, the bastion is not deployed. If you do chosse to deploy it, you will need to handle the patching.

*Q*: Deployment & maintenance as a service ?

*A*: If Discngine technical staff can be provided with sufficiant AWS privileges (AWS administration privileges), deployment and maintenance can be provided as extra support.

*Q*: Staff will be needing access to cluster, should we pay for additionnal web seats ?

*A*: No. Admin access are free, even in production.

*Q*: How about structure upload documentation/requirement ?

*A*: A full requirement list and documentation exists, please ask your 3decision sale contact to provide it.

*Q*: Can continuous deployment can be configured ?

*A*: No, CD only concerns the 3decision SaaS version. Updates will be deployed by the customer cluster manager. Update commands and instructions will be provided out of the box. Discngine will provide support for the updates too.

*Q*: Will 3decision make HTTP calls to internet websites?

*A*: Yes, 3decision synchronizes with public structures made available by the RCSB PDB (Research Collaboratory for Structural Bioinformatics PDB). The data synchronization uses the Rsync protocol.

3decision calls the following domains:

  * `rsync.ebi.ac.uk` on port 873
  * `rsync.wwpdb.org` on ports 873 and 33444

==== Testing/verification

*Q*: Support of Automated System Verification test cases?

*A*: Currently no automated testing available for now. Smoke tests will arrive later in 2023.

*Q*: Automated health checks ?

*A*: Each 3decision microservice provides a liveness and readiness endpoint but no canary monitoring is provided out of the box. Monitoring probes must be configured by the customer.


==== Database sizing and shapes

*Q*: What are sizing specs for the database ?

*A*: Database shape for up to 20 users (concurrent) t3.xlarge is recommended. This can be increased during the deployment.

Oracle RDS storage is 1Tb (extensible to 3Tb, some customers use up to 2Tb).

*Q*: Sizing of storage:

*A*: EBS: overall storage is ~1.2Tb.

EBS volumes : 8 * 50Go + 1 * 8 Go + 1 * 512 Go

*Q*: what is the minimal kubernetes nodes specs ?

*A*: Customers are using application in different ways, and config may differ.

The minimal configuration is 3 nodes. Shape size should be kept as 3 * t3.xlarge.

*Q*: DB is Amazon ORACLE RDS?

*A*: Yes, ORACLE RDS Standard edition

License is included in the shape AWS (license included, and is charged over AWS consumption)

*Q*: Sizing for cost estimates approach?

*A*: With default sizing, the 3decision environement should cost around 1000euros per month.

The best estimate is done by deploying a temporary 3decision environnement in an AWS sandbox and use AWS finops tools to track the costs for a sort period of time.


==== Storage capacity specifications

*Q*: How much  storage space does a typical (3 Å resolution) CryoEM entry require- including meta data and the corresponding mrc file ?

*A*: This is variable and highly dependent on your data. The mrc files can be over 1GB if the the system includs many protein chains but for typical drug discovery projectsn the CryoEM structure entries are 1-2 Mb and their associated mrc file 30-150 Mb.

*Q*: How much does an Xray based structure, including all data, fill ?

*A*: A typical X-Ray file is between 100Ko and 1Mb. Associated data depends on customer data: Pdf files are within the same range, density maps are a bit larger (1Mb to 10Mb), word documents also within the range of 1Mb, etc.

*Q*: Does Discngine have any average figures to draw on, from existing customers, in regards to amount of cloud storage that will be needed (i.e. in best, worst and most likely scenarios). These figures will be used to calculate expected storage usage, also for inputs to cost drivers and budgeting.

*A*: EBS: overall storage is ~1.2Tb. RDS Oracle: 1Tb (extensible to 3Tb, some customers use up to 2Tb). You can roughly consider that uploading large scale datasets like Alphafold will require 1 additionnal Tb for EBS and 1 additionnal Tb for RDS.
