//Include any predeployment steps here, such as signing up for a Marketplace AMI or making any changes to a Partner account. If there are none leave this file empty.

== Predeployment steps

=== Authentication

During deployment, you are prompted to provide information about your authentication provider. 3decision supports OpenID Connect for both Azure and Okta.

==== Creating an Azure OpenID Connect application

. Sign in to the Azure portal using an account with administrator permissions.
. Choose *Azure Active Directory*.
. Under *App registrations*, choose *New registration*.
. Enter a name for your application (for example, `Discngine 3decision prod`).
. For *Redirect URI*, enter the following. Replace `<your domain>` and `<your_top_level_domain>` in the URI shown with your information (for example, `discngine.com`).

+
`\https://3decision-api.<you_domain>.<your_top_level_domain>/auth/azure/callback`

[start=5]
. Choose *Register*.
. In the *Authentication* section of your application, under *Implicit grant and hybrid flows*, select *ID Token* to enable ID tokens.
. In the *Token configuration* section, add the following optional claims to the ID token:
- `email`
- `prefered_username`
- `family_name`
- `given_name`

. On the *Certificates & secrets* page, generate a new secret and copy it. You'll use it during the Quick Start deployment.
. On the *Overview* page, choose the *Endpoints* tab.
. Copy the URL in *OpenID Connect metadata document*. You'll use it during the Quick Start deployment.

. In the Azure portal, navigate to *Enterprise Applications*
. Choose your 3decision application and open it
. Navigate to *Properties* 
. Set * Assignment required?* to Yes if you want to filter out users that are not a member of this application.

==== Creating an Okta OpenID Connect application

. In the Okta Admin Console, under *Applications*, choose *Applications*.
. Choose *Create app integration*.
. For *Sign In* method, choose *OIDC - OpenID Connect*.
. For the application type, choose *Web Application*.
. Choose *Next*.
. Name the application `3decision prod`.
. For *Grant type*, choose *Client Credentials*.
. Select *Refresh Token*.
. For *Sign-in redirect URI*, enter the following. Replace `<your domain>` and `<your_top_level_domain>` in the URI shown with your information (for example, `discngine.com`).

+
`\https://3decision-api.<you_domain>.<your_top_level_domain>/auth/azure/callback`

[start=8]
. On the *Assignments* tab, under *Assign*, choose *Assign to Groups*. Choose group assignments to manage who will be able to access the application.
. Choose *Save*.
. Copy the secret, as you'll use it during the Quick Start deployment.
. In the upper-right corner of the Okta dashboard, copy the Okta domain in the global header (for example, `example.okta-emea.com`). You'll use it during the Quick Start deployment.

During Quick Start deployment, you can choose `default` as your Okta server ID. 3decision will use the scopes `email`, `profile`, `openid`, and `offline_access` and the claims `email` and `name` from the ID token. For more information, refer to https://help.okta.com/en/prod/Content/Topics/Apps/Apps_App_Integration_Wizard_OIDC.htm[Create OIDC app integrations using AIW].

=== VPC Tagging

If you are deploying 3decision in an existing VPC, ensure that the private subnets have the correct tags. 

The tag *kubernetes.io/role/elb* needs to be added on each public subnet and the tag *kubernetes.io/role/internal-elb* on each private subnet.

The value of the tags should remain empty.

=== Encrypting the Database

The RDS Database created during the deployment is based on a snapshot.
In order to make this snapshot public, the snapshot is not encrypted.

If you would like your database to be encrypted you will have to copy this snapshot into your AWS account first.

This can be done by going to the public tab in the RDS snapshot sections, and searching for **db3dec<version>** and grabbing the latest version.

You can then select it, choose copy in actions, and select the encrypt option.

You will then be able to enter the ARN of your copied snapshot in the CloudFormation parameters. If field is left blank, the unencrypted latest snapshot will be used.

=== FAQ before deployment

*Q*: Will 3decision make HTTP calls to internet websites?

*A*: Yes, 3decision synchronizes with public structures made available by the RCSB PDB (Research Collaboratory for Structural Bioinformatics PDB). The data synchronization uses the Rsync protocol. 

3decision calls the following domains:

  * `rsync.ebi.ac.uk` on port 873
  * `rsync.wwpdb.org` on ports 873 and 33444

*Q*: Why does Azure require additional claims and not Okta?

*A*: Azure requires additional claims for 3decision to work with Azure. The default Okta ID token claims are not enough.
